sudo: false
before_install:
 # CMake install taken from <https://github.com/stnava/ANTs/blob/master/.travis.yml>
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://www.cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh; sh cmake-3.2.0-rc1-Linux-x86_64.sh --skip-license --prefix=${HOME}; export PATH=$HOME/bin/:$PATH; fi
install:
  - openssl aes-256-cbc -K $encrypted_1a8bbac7b055_key -iv $encrypted_1a8bbac7b055_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - git clone git://github.com/InsightSoftwareConsortium/ITK.git
  - COMMIT_MESSAGE="ITK compilation on `date "+%Y-%m-%d %H:%M:%S"` from
    `git --git-dir='ITK/.git' log -n 1 --format='commit %h - %s'`"
script:
  - mkdir ITK-build
  - cd ITK-build
  # Build ITK
  - cmake ../ITK && make -j4
  - mkdir -p ../build/ITK
  - ITK_DESTDIR=`( cd ../build/ITK && pwd )`
  - make DESTDIR=$ITK_DESTDIR install
  - cd $ITK_DESTDIR
  - git init
  - git add -f .
  - 'git commit -m "${COMMIT_MESSAGE}"'
  - git push -f git@github.com:CBL-OROIN/ITK-builds.git master:master
